### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by andrewc910** [buttercloud/tookan_ruby_api#2]
Gemfile: 
gem 'tookan_ruby_api', github: 'buttercloud/tookan_ruby_api'

Bundle install && list:
Using tookan_ruby_api 0.1.1 from https://github.com/buttercloud/tookan_ruby_api.git (at master@8a80167) (Your latest commit)

Console:
```irb(main):001:0> **c = Tookan::Client.new**
Traceback (most recent call last):
        1: from (irb):1
NameError (uninitialized constant Tookan)
irb(main):002:0> **require 'tookan_ruby_api'**
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):2:in `rescue in irb_binding'
LoadError (cannot load such file -- tookan_ruby_api)
**irb(main):003:0> require 'tookan'**
Traceback (most recent call last):
        2: from (irb):3
        1: from (irb):3:in `rescue in irb_binding'
LoadError (cannot load such file -- dotenv/load)
```

In controller file for testing:
'require tookan_ruby_api' -> cannot load such file -- tookan_ruby_api
'require tookan' -> cannot load such file -- dotenv/load
And when i don't have the require tookan, i still can't access the classes via Tookan::Client.new

At this point, i am pretty stumped. Never had an issue like this before.

**Comment by pollinoco** [comment]
> Gemfile:
> gem 'tookan_ruby_api', github: 'buttercloud/tookan_ruby_api'
> 
> Bundle install && list:
> Using tookan_ruby_api 0.1.1 from https://github.com/buttercloud/tookan_ruby_api.git (at master@8a80167) (Your latest commit)
> 
> Console:
> 
> ```
> Traceback (most recent call last):
>         1: from (irb):1
> NameError (uninitialized constant Tookan)
> irb(main):002:0> **require 'tookan_ruby_api'**
> Traceback (most recent call last):
>         2: from (irb):2
>         1: from (irb):2:in `rescue in irb_binding'
> LoadError (cannot load such file -- tookan_ruby_api)
> **irb(main):003:0> require 'tookan'**
> Traceback (most recent call last):
>         2: from (irb):3
>         1: from (irb):3:in `rescue in irb_binding'
> LoadError (cannot load such file -- dotenv/load)
> ```
> 
> In controller file for testing:
> 'require tookan_ruby_api' -> cannot load such file -- tookan_ruby_api
> 'require tookan' -> cannot load such file -- dotenv/load
> And when i don't have the require tookan, i still can't access the classes via Tookan::Client.new
> 
> At this point, i am pretty stumped. Never had an issue like this before.


Hello, how did you solve this?
